# -*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VT_DDrywHf8f0GygEJHH6-8zlkkDGkgF

# 💰 Sistema de Controle Financeiro em Python

Este projeto é um sistema simples de controle financeiro desenvolvido em Python, com execução via terminal.

## 🚀 Funcionalidades

- Adicionar transações (entrada e saída)
- Listar transações
- Calcular saldo
- Filtrar por categoria
- Salvar e carregar dados automaticamente

## 🧠 Conceitos utilizados

- Estruturas de dados (listas e dicionários)
- Funções
- Condicionais e loops
- Manipulação de arquivos com JSON

## ▶️ Como usar

Execute o código abaixo e utilize o menu interativo para gerenciar suas transações financeiras.
"""

import json
import os

transacoes = []
ARQUIVO = "dados.json"

def salvar_dados():
    with open(ARQUIVO, "w") as f:
        json.dump(transacoes, f, indent=4)

def carregar_dados():
    global transacoes

    if os.path.exists(ARQUIVO):
        with open(ARQUIVO, "r") as f:
            transacoes = json.load(f)

def adicionar_transacao():
    nome = input("Nome da transação: ")

    # tratamento de erro no valor
    try:
        valor = float(input("Valor: "))
    except:
        print("❌ Valor inválido! Digite um número.")
        return

    tipo = input("Tipo (entrada/saida): ").lower()

    if tipo not in ["entrada", "saida"]:
        print("❌ Tipo inválido! Use 'entrada' ou 'saida'.")
        return

    categoria = input("Categoria: ")

    transacao = {
        "nome": nome,
        "valor": valor,
        "tipo": tipo,
        "categoria": categoria
    }

    transacoes.append(transacao)
    salvar_dados()

    print("✅ Transação adicionada com sucesso!")

def listar_transacoes():
    if not transacoes:
        print("⚠️ Nenhuma transação encontrada.")
        return

    print("\n📋 Lista de Transações:\n")

    for i, t in enumerate(transacoes, start=1):
        print(f"{i}. 💰 {t['nome']} | R${t['valor']} | {t['tipo']} | {t['categoria']}")

def calcular_saldo():
    saldo = 0

    for t in transacoes:
        if t["tipo"] == "entrada":
            saldo += t["valor"]
        else:
            saldo -= t["valor"]

    print(f"\n💰 Saldo atual: R${saldo}")

def filtrar_categoria():
    categoria = input("Digite a categoria: ")

    filtradas = [t for t in transacoes if t["categoria"] == categoria]

    if not filtradas:
        print("⚠️ Nenhuma transação encontrada nessa categoria.")
        return

    print(f"\n🔎 Transações na categoria '{categoria}':\n")

    for t in filtradas:
        print(f"💰 {t['nome']} | R${t['valor']} | {t['tipo']}")

def menu():
    carregar_dados()

    while True:
        print("\n=== 💰 MENU FINANCEIRO ===")
        print("1 - Adicionar transação")
        print("2 - Listar transações")
        print("3 - Ver saldo")
        print("4 - Filtrar por categoria")
        print("5 - Sair")

        opcao = input("Escolha uma opção: ")

        if opcao == "1":
            adicionar_transacao()
        elif opcao == "2":
            listar_transacoes()
        elif opcao == "3":
            calcular_saldo()
        elif opcao == "4":
            filtrar_categoria()
        elif opcao == "5":
            print("👋 Saindo...")
            break
        else:
            print("❌ Opção inválida!")

menu()